version: 2

workflows:
  version: 2
  test:
    jobs:
      - small
      - medium
      - medium-plus
      - large
  waiter1:
    jobs:
      - wait1
      - wait5
  waiter2:
    jobs:
      - wait1
      - wait5


job-default: &job-default
  docker:
    - image: circleci/ruby:2.4.1
  steps:
    - run: echo $CIRCLE_JOB 

waiter: &waiter
  machine: true
  steps:
    - run: |
        echo $SLEEP
        date
        sleep $SLEEP
        date
        echo 'Done sleeping'

jobs:
  small:
    <<: *job-default
    resource_class: small
  medium:
    <<: *job-default
    resource_class: medium
  medium-plus:
    <<: *job-default
    resource_class: medium+
  large:
    <<: *job-default
    resource_class: large

  wait1:
    <<: *waiter
    environment:
      SLEEP: 1
  wait5:
    <<: *waiter
    environment:
      SLEEP: 5
