version: 2

workflows:
  version: 2
  test:
    jobs:
      - small
      - medium
      - medium-plus
      - large
  other:
    jobs:
      - other

job-default: &job-default
  docker:
    - image: circleci/ruby:2.4.1
  steps:
    - run: echo $CIRCLE_JOB  

jobs:
  small:
    <<: *job-default
    resource_class: small
  medium:
    <<: *job-default
    resource_class: medium
  medium-plus:
    <<: *job-default
    resource_class: medium+
  large:
    <<: *job-default
    resource_class: large
    
  other:
    <<: *job-default