version: 2

workflows:
  version: 2
  resource_class_jobs:
    jobs:
      - small
      - medium
      - medium-plus
      - large
  machine_jobs:
    jobs:
      - machine1
  feature_jobs:
    jobs:
      - write_workspace
      - use_workspace:
          requires:
            - write_workspace

job-default: &job-default
  docker:
    - image: circleci/ruby:2.4.1
  steps:
    - run: echo $CIRCLE_JOB 

machine: &machine
  machine: true
  steps:
    - run: |
        echo $SLEEP
        date
        sleep $SLEEP
        date
        echo 'Done sleeping'

jobs:
  small:
    <<: *job-default
    resource_class: small
  medium:
    <<: *job-default
    resource_class: medium
  medium-plus:
    <<: *job-default
    resource_class: medium+
  large:
    <<: *job-default
    resource_class: large

  machine1:
    <<: *machine
    environment:
      SLEEP: 1

  write_workspace:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/foo/bar/
    steps:
      - run: mkdir stuff
      - run: echo 5 >./stuff/thing
      - persist_to_workspace:
          root: .
          paths:
            - stuff
