version: 2

workflows:
  version: 2
  test:
    jobs:
      - small

job-default: &job-default
  docker:
    - image: circleci/ruby:2.4.1
  steps:
    - run: echo $CIRCLE_JOB  

jobs:
  small:
    <<: *job-default
    resource_class: small
    
