version: 2

workflows:
  version: 2
  test:
    jobs:
      - small

jobs:
  small:
    docker:
      image: circleci/ruby:2.4.1
    resource_class: small
    steps:
      - echo 'I ran in a small'
      - echo $CIRCLE_COMPARE_URL
