version: 2

workflows:
  version: 2
  resource_class_jobs:
    jobs:
      - small
      - medium
      - medium-plus
      - large
  machine_jobs:
    jobs:
      - machine1

default-container: $default-container
  - image: image: circleci/ruby:2.4.1

job-default: &job-default
  docker:
    <<: *default-container
  steps:
    - run: echo $CIRCLE_JOB 

machine: &machine
  machine: true
  steps:
    - run: |
        echo $SLEEP
        date
        sleep $SLEEP
        date
        echo 'Done sleeping'

jobs:
  small:
    <<: *job-default
    resource_class: small
  medium:
    <<: *job-default
    resource_class: medium
  medium-plus:
    <<: *job-default
    resource_class: medium+
  large:
    <<: *job-default
    resource_class: large

  machine1:
    <<: *machine
    environment:
      SLEEP: 1
